# Generated by Django 3.0.6 on 2020-06-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20200530_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citieslist',
            name='city_info',
        ),
        migrations.RemoveField(
            model_name='streetslist',
            name='street_info',
        ),
    ]
