# Generated by Django 3.0.6 on 2020-06-04 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20200604_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryuseraddress',
            name='city_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.CitiesList'),
        ),
        migrations.AddField(
            model_name='libraryuseraddress',
            name='street_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.StreetsList'),
        ),
    ]
