# Generated by Django 3.0.6 on 2020-06-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20200604_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libraryuseraddress',
            old_name='library_user_info',
            new_name='library_user',
        ),
    ]
